//
// Created by Christopher Jung on 04.12.20.
//


#define TYPE_INT 0
#define TYPE_CHAR 1
#define TYPE_VOID 2
//#define TYPE_STRING 4

#define END_OF_FILE 0
#define AUTO 4
#define BREAK 5
#define CASE 6
#define CHAR 7
#define CONST 8
#define CONTINUE 9
#define DEFAULT 10
#define DO 11
#define DOUBLE 12
#define ELSE 13
#define ENUM 14
#define EXTERN 15
#define FLOAT 16
#define FOR 17
#define GOTO 18
#define IF_STATEMENT 19
#define INLINE 20
#define INT 21
#define LONG 22
#define REGISTER 23
#define RESTRICT 24
#define RETURN 25
#define SHORT 26
#define SIGNED 27
#define SIZEOF 28
#define STATIC 29
#define STRUCT 30
#define SWITCH 31
#define TYPEDEF 32
#define UNION 33
#define UNSIGNED 34
#define VOID 35
#define VOLATILE 36
#define WHILE 37
#define ALIGNAS 38
#define ALIGNOF 39
#define ATOMIC 40
#define BOOL 41
#define COMPLEX 42
#define GENERIC 43
#define IMAGINARY 44
#define NORETURN 45
#define STATICASSERT 46
#define THREADLOCAL 47
#define DIGIT_SEQUENCE 48
#define CONSTANT 49
#define IDENTIFIER 50
#define STRING_LITERAL 51
#define LEFT_PAREN 52
#define RIGHT_PAREN 53
#define LEFT_BRACKET 54
#define RIGHT_BRACKET 55
#define LEFT_BRACE 56
#define RIGHT_BRACE 57
#define LESS 58
#define LESS_EQUAL 59
#define GREATER 60
#define GREATER_EQUAL 61
#define LEFT_SHIFT 62
#define RIGHT_SHIFT 63
#define PLUS 64
#define PLUS_PLUS 65
#define MINUS 66
#define MINUS_MINUS 67
#define STAR 68
#define DIV 69
#define MOD 70
#define AND 71
#define OR 72
#define AND_AND 73
#define OR_OR 74
#define CARET 75
#define NOT 76
#define TILDE 77
#define QUESTION 78
#define COLON 79
#define SEMI 80
#define COMMA 81
#define ASSIGN 82
#define STAR_ASSIGN 83
#define DIV_ASSIGN 84
#define MOD_ASSIGN 85
#define PLUS_ASSIGN 86
#define MINUS_ASSIGN 87
#define LEFT_SHIFT_ASSIGN 88
#define RIGHT_SHIFT_ASSIGN 89
#define AND_ASSIGN 90
#define XOR_ASSIGN 91
#define OR_ASSIGN 92
#define EQUAL 93
#define NOT_EQUAL 94
#define ARROW 95
#define DOT 96
