//
// Created by chris on 21.01.21.
//

#include "../elements/Element.h"
#include "../elements/Assignment.h"
#include "../elements/Binary.h"
#include "../elements/Block.h"
#include "../elements/Break.h"
#include "../elements/Call.h"
#include "../elements/CompareBinary.h"
#include "../elements/Constant.h"
#include "../elements/Continue.h"
#include "../elements/Declaration.h"
#include "../elements/Declarator.h"
#include "../elements/DirectDeclarator.h"
#include "../elements/Dumpable.h"
#include "../elements/Expression.h"
#include "../elements/GoTo.h"
#include "../elements/Identifier.h"
#include "../elements/If.h"
#include "../elements/Choose.h"
#include "../elements/LabeledStatement.h"
#include "../elements/LogicalAnd.h"
#include "../elements/LogicalOr.h"
#include "../elements/Method.h"
#include "../elements/Number.h"
#include "../elements/Operator.h"
#include "../elements/ParameterDirectDeclarator.h"
#include "../elements/ParameterTypeList.h"
#include "../elements/Return.h"
#include "../elements/Select.h"
#include "../elements/Sizeof.h"
#include "../elements/Statement.h"
#include "../elements/StringLiteral.h"
#include "../elements/StructType.h"
#include "../elements/Type.h"
#include "../elements/Unary.h"
#include "../elements/Unit.h"
#include "../elements/While.h"
